---

- name: Install Smartmontools
  ansible.builtin.apt:
    name: smartmontools
    update_cache: true

- name: Remove zabbix-smartctl from sudoers file
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: 'zabbix.*smartctl'
    validate: /usr/sbin/visudo -cf %s

- name: Allow zabbix to read S.M.A.R.T values (in /etc/sudoers.d)
  community.general.sudoers:
    name: sudoers_zabbix_smartctl
    user: zabbix
    commands:
      - /usr/sbin/smartctl
    nopassword: true
    sudoers_path: /etc/sudoers.d

- name: Add UserParameter for smartctl self-test
  ansible.builtin.template:
    src: smart_selftests.conf.j2
    dest: /etc/zabbix/zabbix_agent2.d/smart_selftests.conf
    owner: zabbix
    group: zabbix
    mode: '0644'
  notify:
    - Restart zabbix-agent
  become: true
